### ISSUE TITLE
`get_charge()` does queries whose results are never used.

### ISSUE THREAD

**Issue by dreirund** [ashish-kus/batfetch#5]
I just hat a look into the `batfetch` `bash`-script.

In `get_charge()` you set `charge="$(cat /sys/class/power_supply/BAT*/capacity)%"`, `Energy_now="$(cat /sys/class/power_supply/BAT*/energy_now)"` and `Draw="$(cat /sys/class/power_supply/BAT*/power_now)"`, but use only `charge`. The other two are obsolete.

Regards!

**Comment by ashish-kus** [comment]
Thank you for taking the time to review the batfetch bash-script and for pointing out the issue regarding the variables charge, Energy_now, and Draw. I truly appreciate your attention to detail and your valuable input.

I apologize for any confusion caused by the presence of these unused variables. I must clarify that they were intended to be part of a feature I am currently working on. Unfortunately, due to time constraints, I have not yet implemented this feature in the script.

Rest assured, I have taken note of your feedback, and I am actively working on incorporating these variables along with additional options in the upcoming version of the project. You will be able to see these changes in the code very soon.

Your contribution to the project is highly valued, and I am grateful for your continued support in making batfetch even better. 
Thank you.
